### ISSUE TITLE
Create Spend Activity (BACK END) 

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#578]
__Is this part of a User Journey?__

https://github.com/yalla-coop/tempo/issues/572

---

### Acceptance Criteria:
- [ ] Ensure database is updated following latest schema https://github.com/yalla-coop/tempo/issues/577
- [ ] Back end validation of fields
- [ ] Query to store the activity 
- [ ] Query to fetch the activity details if the activity already exists i.e. editing (might overlap with existing query / can use existing query to get the spend activity to show publicly?) 
- [ ] Query to update activity 
- [ ] Ensure images if replaced then the old images should be deleted 
- [ ] Connect with front end 
- [ ] Use Image service #573 

**Dates**
This is a more complicated bit, so feel free to spin out into separate issue if needed
- [ ] Store series of dates and times, whether recurring etc - outlined more in the database issue https://github.com/yalla-coop/tempo/issues/577

**Booking codes**
This is a more complicated bit, so feel free to spin out into separate issue if needed
- [ ] Store all booking codes following the database architecture https://github.com/yalla-coop/tempo/issues/577
- [ ] Query to fetch number of codes used for this activity so far 
- [ ] Query to fetch live codes and render in text area if editing an existing activity
