### ISSUE TITLE
Update Account Details 

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#581]
__Is this part of a User Journey?__

_As a member I can update my account details_
_As an earn group I can update our account details_
_As a spend venue I can update our account details_
_As a staff member I can edit some of an Earn Group's account details_
_As a staff member I can edit some of a Spend Venue's account details_

---

### Acceptance Criteria:
- [x] Create back end service for user to update their own account details https://github.com/yalla-coop/tempo/issues/583
- [x] Create back end service for staff member to update another user's account details https://github.com/yalla-coop/tempo/issues/583
- [x] Create query to fetch the details for that user (password would just be dots so they can't see this) https://github.com/yalla-coop/tempo/issues/583
- [x] Front end for member to edit their account details  https://github.com/yalla-coop/tempo/issues/582
- [x] Front end for earn group to edit their account details https://github.com/yalla-coop/tempo/issues/582
- [x] Front end for spend venue to edit their account details  https://github.com/yalla-coop/tempo/issues/582
- [x] For staff, these details are included in 
     - [x] Create / Edit Spend Venue https://github.com/yalla-coop/tempo/issues/579
     - [x] Create / Edit Earn Group  https://github.com/yalla-coop/tempo/issues/580
