### ISSUE TITLE
Create / Edit Spend Venue (BACK END) 

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#585]
__Is this part of a User Journey?__

https://github.com/yalla-coop/tempo/issues/579

---

### Acceptance Criteria:
- [ ] Ensure database is updated following latest schema https://github.com/yalla-coop/tempo/issues/577
- [ ] Back end validation of fields
- [ ] Query to store the new spend venue 
- [ ] Query to fetch the activity details (except password) if the spend venue already exists i.e. editing (might overlap with existing query / can use existing query to get the spend venue to show publicly?) 
- [ ] Query to update spend venue 
- [ ] Ensure images if replaced then the old images should be deleted 
- [ ] Connect with front end 
- [ ] Use Image service #573 
- [ ] Use Account details service for that part of the data https://github.com/yalla-coop/tempo/issues/583
