### ISSUE TITLE
Create / edit Earn Group profile form (BACK END)

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#587]
This covers the back end set up for 
- [ ] Staff to create / edit earn group profile
- [ ] Earn groups to create / edit their profile

__Is this part of a User Journey?__

https://github.com/yalla-coop/tempo/issues/580

---

### Acceptance Criteria:
- [ ] Ensure database is updated following latest schema https://github.com/yalla-coop/tempo/issues/577
- [ ] Back end validation of fields
- [ ] Query to update the earn group
- [ ] Query to fetch the earn group details (except password) that we already have
- [ ] Query to update earn group
- [ ] Ensure images if replaced then the old images should be deleted 
- [ ] Connect with front end for staff and earn groups
- [ ] Use Image service #573 
- [ ] Use Account details service for that part of the data https://github.com/yalla-coop/tempo/issues/583
