### ISSUE TITLE
Create all Programme Pages (FRONT END)

### ISSUE THREAD

**Issue by thejoefriel** [yalla-coop/tempo#602]
__Is this part of a User Journey?__

https://github.com/yalla-coop/tempo/issues/600
---

### Acceptance Criteria:

- [x] Create / edit programme
    - [x] Validation to ensure all required fields are filled in 
    - [x] Redirect to the programme page for this programme when user clicks Create programme button

    **For editing**
    - [x] If there are already values then pre-fill the inputs with these values
    - [x] Change relevant parts of copy (e.g. title is Edit Programme) 
    - [x] Use Save component for when changes are completed and user hits save changes: https://github.com/yalla-coop/tempo/issues/601

- [x] Create Programmes page **(Ramy will work on this alongside with #605 ).**
     - [x] Use updated table component https://github.com/yalla-coop/tempo/issues/596
     - [x] Render stats (set up how you plan to receive it from redux, including loading features) 
     - [ ] Table sorting
         - [ ] Programme alphabetically
         - [ ] Earn Groups (largest to smallest)
         - [ ] Members (largest to smallest)
         - [ ] % Spent (largest to smallest)
         - [ ] % Gifted (largest to smallest) 
         - [ ] Status alphabetically
         - [ ] date opened (oldest to newest)
         - [ ] end date (oldest to newest)
         - [ ] region alphabetically 
         - [ ] Focus alphabetically

- [x] Individual Programmes page 
     - [x] Render stats (set up how you plan to receive it from redux, including loading features) 
     - [x] Copy same Requests tables we use on the Time Requests page 
     - [x] If new (i.e. directed from create programme) then show successfully created message

- [x] Individual Programme - Earn Groups
     - [ ] Render stats (set up how you plan to receive it from redux, including loading features) 
     - [ ] Page is effectively same as Earn Groups page so copy across style for consistency. This should be done in issue #604

- [x] Add Earn Group page
     - [x] Similar style to adding a member for Earn Groups so copy that style for consistency
